In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
class LogisticRegression():
    def __init__(self, lr=1e-3, n_iters=1000):
        self.lr = lr
        self.n_iters = n_iters
        self.w = None
        self.b = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.w = np.zeros(n_features)
        self.b = 0

        for _ in range(self.n_iters):
            y_pred = sigmoid(np.dot(X, self.w) + self.b)

            dw = (1 / n_samples) * np.dot(X.T, y_pred - y)
            db = (1 / n_samples) * np.sum(y_pred - y)

            self.w -= self.lr * dw
            self.b -= self.lr * db

    def predict(self, X):
        y_pred = sigmoid(np.dot(X, self.w) + self.b)
        y_pred = [1 if i > 0.5 else 0 for i in y_pred]

        return y_pred

In [4]:
def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)

In [5]:
bc = datasets.load_breast_cancer()
X, y = bc.data, bc.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

In [6]:
X.shape, y.shape

((569, 30), (569,))

In [7]:
X[42], y[42]

(array([1.907e+01, 2.481e+01, 1.283e+02, 1.104e+03, 9.081e-02, 2.190e-01,
        2.107e-01, 9.961e-02, 2.310e-01, 6.343e-02, 9.811e-01, 1.666e+00,
        8.830e+00, 1.049e+02, 6.548e-03, 1.006e-01, 9.723e-02, 2.638e-02,
        5.333e-02, 7.646e-03, 2.409e+01, 3.317e+01, 1.774e+02, 1.651e+03,
        1.247e-01, 7.444e-01, 7.242e-01, 2.493e-01, 4.670e-01, 1.038e-01]), 0)

In [8]:
np.unique(y)

array([0, 1])

In [9]:
model = LogisticRegression(lr=1e-4)
model.fit(X_train, y_train)

In [10]:
model.w, model.b

(array([ 3.15267538e-02,  4.38592690e-02,  1.82394637e-01,  7.27657289e-02,
         2.81683690e-04, -1.58921860e-04, -5.94869592e-04, -2.47270611e-04,
         5.51932783e-04,  2.26761495e-04,  1.51071202e-04,  3.05608006e-03,
        -1.13197589e-03, -8.16912730e-02,  1.44483806e-05, -4.65383514e-05,
        -7.39608956e-05, -1.01074526e-05,  5.54703739e-05,  1.84514942e-06,
         3.33636766e-02,  5.58146134e-02,  1.82897269e-01, -9.88462272e-02,
         3.48754542e-04, -6.74411296e-04, -1.27433782e-03, -2.94192307e-04,
         7.76822709e-04,  1.96607498e-04]), 0.004111914763563402)

In [11]:
y_pred = model.predict(X_test)
accuracy(y_test, y_pred)

0.9298245614035088