In [1]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
class SVM():
    def __init__(self, lr=1e-3, lambda_param=1e-2, n_iters=1000):
        self.lr = lr
        self.lambda_param = lambda_param
        self.n_iters = n_iters
        self.w = None
        self.b = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        y = np.array([-1 if i <= 0 else 1 for i in y])

        self.w = np.zeros(n_features)
        self.b = 0

        for _ in range(self.n_iters):
            for i, x_i in enumerate(X):
                if y[i] * (np.dot(x_i, self.w) - self.b) >= 1:
                    self.w -= self.lr * (2 * self.lambda_param * self.w)
                else:
                    self.w -= self.lr * (2 * self.lambda_param * self.w - np.dot(x_i, y[i]))
                    self.b -= self.lr * y[i]

    def predict(self, X):
        return np.sign(np.dot(X, self.w) - self.b)

In [3]:
def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)

In [4]:
bc = datasets.load_breast_cancer()
X, y = bc.data, bc.target
y = np.where(y == 0, -1, 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [5]:
X.shape, y.shape

((569, 30), (569,))

In [6]:
X[42], y[42]

(array([1.907e+01, 2.481e+01, 1.283e+02, 1.104e+03, 9.081e-02, 2.190e-01,
        2.107e-01, 9.961e-02, 2.310e-01, 6.343e-02, 9.811e-01, 1.666e+00,
        8.830e+00, 1.049e+02, 6.548e-03, 1.006e-01, 9.723e-02, 2.638e-02,
        5.333e-02, 7.646e-03, 2.409e+01, 3.317e+01, 1.774e+02, 1.651e+03,
        1.247e-01, 7.444e-01, 7.242e-01, 2.493e-01, 4.670e-01, 1.038e-01]), -1)

In [7]:
np.unique(y)

array([-1,  1])

In [8]:
model = SVM()
model.fit(X_train, y_train)

In [9]:
model.w, model.b

(array([ 3.83823814e+00,  3.65957605e-01,  1.71484598e+01,  5.59970243e+00,
        -7.63409349e-03, -1.87962320e-01, -2.92659485e-01, -1.17698412e-01,
        -2.34414484e-03,  6.83456045e-03,  6.14403888e-04, -1.95288436e-02,
        -6.76545927e-01, -1.12561942e+01, -5.79518230e-03, -5.46204909e-02,
        -7.07367399e-02, -1.52036826e-02, -1.11786085e-02, -4.17249376e-03,
         3.99655823e+00, -1.04857309e+00,  1.45531289e+01, -7.52512927e+00,
        -3.71040849e-02, -6.01134309e-01, -7.37737372e-01, -1.92540983e-01,
        -1.01609255e-01, -3.33491710e-02]), -4.923999999999979)

In [10]:
y_pred = model.predict(X_test)
accuracy(y_test, y_pred)

0.956140350877193